######################################################################
# Automatically generated by qmake (3.0) Mon Jan 27 00:43:36 2014
######################################################################

QT += widgets
TEMPLATE = app
TARGET = joddial
INCLUDEPATH += . src

# Input
HEADERS += src/joddial.h
SOURCES += src/joddial.cpp src/main.cpp

# Output
DESTDIR = build
OBJECTS_DIR = build
MOC_DIR = build
RCC_DIR = build
UI_DIR = build