######################################################################
# Automatically generated by qmake (3.0) Sun Jan 19 15:08:31 2014
######################################################################

QT += widgets
TEMPLATE = app
TARGET = joddial
INCLUDEPATH += .

# Input
HEADERS += joddial.h
SOURCES += main.cpp joddial.cpp
